name: apiverve_ethereum
description: Ethereum Price is a simple tool for getting the current price of Ethereum. It returns the current price, market cap, 24-hour trading volume, and 24-hour price change in any currency.
version: 1.1.14
homepage: https://apiverve.com/marketplace/ethereum?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/ethereum-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
